version: '3'

services:
  rinha_api1: &rinha_api1
    build: .
    container_name: rinha_api1
    network_mode: host
    environment:
      PORT: ":3001"
      DATABASE_URL: "postgres://myuser:mypassword@localhost:5432/mydatabase?sslmode=disable"
    entrypoint: ./server
    depends_on:
      postgres:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "50MB"

  rinha_api2:
    <<: *rinha_api1
    container_name: rinha_api2 
    environment:
      PORT: ":3002"
      DATABASE_URL: "postgres://myuser:mypassword@localhost:5432/mydatabase?sslmode=disable"

  postgres:
    image: postgres:latest
    container_name: rinha_postgres
    command: postgres  -c 'work_mem=256MB' -c 'max_connections=255' -c 'log_error_verbosity=terse'
    network_mode: host
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql      
    deploy:
      resources:
        limits:
          cpus: '0.6'
          memory: '350MB'

  nginx:
    image: nginx:latest
    container_name: rinha_nginx
    network_mode: host
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - rinha_api1
      - rinha_api2
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "50MB" 
