// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlc

import (
	"database/sql"
)

type Client struct {
	ID           int32
	AccountLimit int32
	Balance      int32
}

type Transaction struct {
	ID          int32
	ClientID    int32
	Value       int32
	Type        string
	Description string
	CreatedAt   sql.NullTime
}
